name: Release Portal
on:
    push:
        tags:
            - '*'
    workflow_dispatch:

jobs:
    build:
        name: Build Remote
        runs-on: ubuntu-22.04
        steps:
            - name: Check out source code
              uses: actions/checkout@v4
            # Generate version information
            - name: Generate version text file
              run: git describe --tag > version.txt
            # Set an environment variable to the tag we want to use to describe this release.
            - name: Get tag environment variable.
              run: echo "RELEASE_VERSION=$(git describe --tag | sed s/v// | sed -E s/[\.]/\\\\\./g)" >> $GITHUB_OUTPUT
              id: release-version
            - name: Replace Cargo.toml version with tag.
              run: sed -i -E 's/^version.*$/version = "${{ steps.release-version.outputs.RELEASE_VERSION }}"/' Cargo.toml
            # Compile rust code
            - name: Build rust code.
              run: chmod +x ./cross_compile.sh && ./cross_compile.sh